services:
  sup-invoices-service-api:
    container_name: sup-invoices-service-api
    build:
      context: .
    env_file:
      - .env
    ports:
      - "12345:80"
    networks:
      - local-straker
    restart: unless-stopped

networks:
  local-straker:
    name: development_local-straker
    driver: bridge
