services:
  sup-invoices-service-api:
    container_name: sup-invoices-service-api
    build:
      context: .
    env_file:
      - .env
    ports:
      - "12345:80"
    networks:
      local-straker:
        ipv4_address: 172.20.0.47
    extra_hosts:
      local-buglog.strakergroup.com: 172.17.0.1

networks:
  local-straker:
    name: development_local-straker
    external: true
